version: '3.9'

networks:
  greenfest-bot-network:
    name: greenfest-bot-network
    driver: bridge

volumes:
  greenfest-bot-redis-volume:
  greenfest-bot-postgres-volume:

services:
  db:
    image: postgres:14.5-alpine
    container_name: greenfest-bot-db
    restart: always
    ports: ["5001:5432"]
    environment:
      POSTGRES_DB: greenfest-bot
      POSTGRES_USER: greenfest-bot
      POSTGRES_PASSWORD: greenfest-bot
      POSTGRES_PORT: 5000
    volumes:
      - greenfest-bot-postgres-volume:/var/lib/postgresql/data
    networks:
      - greenfest-bot-network